FROM eclipse-temurin:21-jdk-alpine

LABEL maintainer="surajpaudel4833@gmail.com"
LABEL description="Spring Security Example"
LABEL version="1.0"

COPY target/SpringSecurityDeepDive-0.0.1-SNAPSHOT.jar SpringSecurityDeepDive.jar

ENTRYPOINT ["java", "-jar", "SpringSecurityDeepDive.jar"]